### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by YoColdRain** [anilbajaj78/plugin.video.ozee#5]
definitely not an issue, but just wanted to say that you saved me whole bunch of time.  I started working on this addon and got tvshows done, but should of just looked here on github first.  

btw, may I ask what you were doing with ozee.py?

**Comment by anilbajaj78** [comment]
Good to hear that I was able to save your time.

In ozee.py, 
1. It displays the hard-coded channel names 
2. On selection of any channel hard-coded URL of respective channel is called, 
3. Return response is JSON, from which Serial Name, image, URL, etc. is captured.
4. The app gives user option for listing the latest episodes or oldest episoded.
5. On user selection URL is formed & queried, from the JSON response, episode list is displayed. 
6. Same logic contiues for displaying episode video detail & displaying video.

I trust that above information will help you. Do let me know if any further information is required. Thanks.
